#!/bin/bash
yum update -y

#Install Amazon EFS utils - this will allow you to mount the NFS filesystem
yum install docker amazon-efs-utils -y

#Creating a mount point for NFS and adding it to the fstab
mkdir -p /mnt/efs-storage

#Change AWS EFS DNS mount it will be FS-XXXXXXX
echo fs-123456789:/ /mnt/efs-storage efs defaults,_netdev 0 0 >> /etc/fstab
mount -a

#Installing Docker and adding worker to the swarm
systemctl start docker
systemctl enable docker
docker swarm join --token ABCDEF123456 1.2.3.4:2377    
